name: Chad Minick | Software Developer
description: "Blog for Chad Minick in which he discusses his interests, Computer Programming, Software Engineering, Web Development and more"
url: http://chadminick.com/
markdown: redcarpet
pygments: true
permalink: /articles/:title.html
excerpt_separator: "<!--MORE-->"
paginate: 5
paginate_path: page/:num
tag_page_layout: tag_page
tag_page_dir: tag